#!/bin/bash
/usr/bin/Xvfb :99 -screen 0 1024x768x16 &
export DISPLAY=:99

# Give Svfb some time to start up
sleep 5

/home/mistpl/inderr-receiver/venv/bin/python /home/mistpl/inderr-receiver/main.py >> /home/mistpl/inderr-receiver/papis.log 2>&1
